### ISSUE TITLE
python setup.py egg_info failed when manually installing EMS

### ISSUE THREAD

**Issue by valerioferretti92** [openbaton/ems#19]
I am trying to deploy the iperf network service on a server that seems to be properly running both openbaton and openstack. The problem I have encountered is that when deploying such network service from OpenBaton dashboard (or command line) both network service record and virtual network function records get stuck in the ERROR state "org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Timeout waiting for EMS: iperf-server-9598388".
It seemed to me that the problem was related to EMS inside VNF (Virtual Network Function) so I sshed into the virtual machine running the VNF iperf-server and I tried to manually install EMS using your instructions to better understand what the problem was. All commands run just fine but "pip install openbaton-ems" whose log is the following:

*********************************************************************************************************************
Downloading/unpacking openbaton-ems
  Getting page https://pypi.python.org/simple/openbaton-ems/
  URLs to search for versions for openbaton-ems:
  * https://pypi.python.org/simple/openbaton-ems/
  Analyzing links from page https://pypi.org/simple/openbaton-ems/
    Found link https://files.pythonhosted.org/packages/61/46/65220fe85b6914a3764080a63b79a0ad43603971eae2198ba071bccaf362/openbaton-ems-1.0.3.tar.gz#sha256=b574a7a9fe06cb86427d8b1bea67c3849c24454bbdf8d698d1ad9a025f969c33 (from https://pypi.org/simple/openbaton-ems/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/86/f8/97cf73a527bd6f91cdaca3333624d4a772e01cda51789de93288915c06d5/openbaton-ems-1.0.8.tar.gz#sha256=353f0057929a21c675d846df1d12d1dbaf647440a4439ecbf6a89e79774696b3 (from https://pypi.org/simple/openbaton-ems/), version: 1.0.8
    Found link https://files.pythonhosted.org/packages/8b/28/809b3f408d10a1fddc7ca6a02ad9f62de751f4dbfd7cf780a6bcf45854e4/openbaton-ems-1.0.9.tar.gz#sha256=a63946a5a3f4ed805b92e8d0aaaeeb6c0ea3269acc0bfd627c27ee5150d6ca3a (from https://pypi.org/simple/openbaton-ems/), version: 1.0.9
  Using version 1.0.9 (newest of versions: 1.0.9, 1.0.8, 1.0.3)
  Downloading openbaton-ems-1.0.9.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/8b/28/809b3f408d10a1fddc7ca6a02ad9f62de751f4dbfd7cf780a6bcf45854e4/openbaton-ems-1.0.9.tar.gz#sha256=a63946a5a3f4ed805b92e8d0aaaeeb6c0ea3269acc0bfd627c27ee5150d6ca3a (from https://pypi.org/simple/openbaton-ems/)
  Running setup.py (path:/tmp/pip_build_root/openbaton-ems/setup.py) egg_info for package openbaton-ems
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'

  warnings.warn(msg)

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help

error: invalid command 'egg_info'

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/openbaton-ems
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/openbaton-ems
*********************************************************************************************************************

I am not sure about it but it seems that this problem prevents ems from installing and it causes the VNFM (Virtual Network Function Manager) to timeout while waiting for VNF's EMS to reply. I tried to manually install other version of EMS but still the same problem came up. How can I solve it? Is the problem only related to EMS or it regards also the generic VNFM? Are the warnings about entry_points and install_requires related to the failure? Any help would be very much appreciated. 
NB: It may be worth mentioning that when I sshed to VM running iperf-server VNF I run also the command "sudo apt-get install -y python-pip". This command actually installed pip so it wasn't run automatically during deployment as you say in your guide.
Thank you very much 
Ferretti Valerio

**Comment by ogozman** [comment]
The deployment of ems via pypi has been overhauled later and has been used ever since succesfully
