### ISSUE TITLE
Use of heartbeat_interval parameter in pika causes ems.py to fail.

### ISSUE THREAD

**Issue by nbeijar** [openbaton/ems#22]
According to the changelog of pika (https://github.com/pika/pika/blob/345c9626ff3e79691241ecafe1573d3cf1ae0e5d/CHANGELOG.rst) the heartbeat_interval parameter of pika.ConnectionParameters was removed on 2019-03-26 (it was deprecated on 2017-07-29). Because ems.py uses the heatbeat_interval parameter in its call to pika.ConnectionParameters, an exception "unexpected kwargs: {'heartbeat_interval': 120}" is generated when it tries to connect. This exception is silently ignored but causes the connection to the RabbitMQ server to fail on every retry. Consequently, ems suddenly stopped working in deployments created after 2019-03-26.

**Comment by mpauls** [comment]
Issue fixed in https://github.com/openbaton/ems/commit/7ff56f2b822970c568fac2fd2d7686376713bf10 by forcing the previous pika version 0.13.1.

This version was released as 1.2.2. Depending on your setup you may simply update to this version.
